### ISSUE TITLE
How to downgrade PowerShell in Windows 2012?

### ISSUE THREAD

**Issue by metametadata** [rgl/windows-vagrant#10]
Hello! Is it possible to downgrade PowerShell (current version is 5.1, expected version is 4.0) in `rgl/windows-server-2012-r2-standard-amd64` box?

I've tried `wusa.exe /uninstall /KB:3191564` but it fails. So far it seems that the only option for me is to repack the box without running `provision-powershell.ps1`.

**Comment by rgl** [comment]
Sorry, but I have no idea.

**Comment by metametadata** [comment]
I see, thanks. 

> why you would want to do that

I have a project which must support old machines running Windows 2012 with PowerShell 4. I use Vagrant to run automated test suite which proves such compatibility.

> I will remove it from this repository once I can.

This would be a loss. Maybe consider making it [archived](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/archiving-repositories) instead?

**Comment by rgl** [comment]
This repository wont go away. Its just the master branch that will eventually be modified to be without windows 2012 r2.
