### ISSUE TITLE
make build-windows-windows-2019-virtualbox shows /bin/sh: line 1: 7z: command not found

### ISSUE THREAD

**Issue by dbase123** [rgl/windows-vagrant#13]
Hi.

I get an error message when I execute `make build-windows-2019-virtualbox` command

This is the error message:

rm -rf drivers.tmp
mkdir -p drivers.tmp
wget -P drivers.tmp https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.190-1/virtio-win-0.1.190.iso
--2021-01-07 14:38:58--  https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.190-1/virtio-win-0.1.190.iso
Resolving fedorapeople.org (fedorapeople.org)... 152.19.134.199, 2610:28:3090:3001:5054:ff:fea7:9474
Connecting to fedorapeople.org (fedorapeople.org)|152.19.134.199|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 501745664 (479M) [application/octet-stream]
Saving to: ‘drivers.tmp/virtio-win-0.1.190.iso’

virtio-win-0.1.190.iso                     100%[======================================================================================>] 478.50M  19.2MB/s    in 47s

2021-01-07 14:39:46 (10.1 MB/s) - ‘drivers.tmp/virtio-win-0.1.190.iso’ saved [501745664/501745664]

**7z x -odrivers.tmp drivers.tmp/virtio-win-*.iso
/bin/sh: line 1: 7z: command not found
make: *** [Makefile:164: drivers] Error 127**

To fix this issue: In the Mingw64 Bash Shell, I installed p7zip with this command:

`Bash 'pacman --noconfirm -Sy p7zip'`

I just wanted to let you know so you can decide if you want to reproduce the problem and the solution and decide if you want to update the readme/instructions:-)

Best Regards

**Comment by rgl** [comment]
ah thank you! indeed, the host system needs to have 7zip installed (either in msys2, or in windows using chocolatey).

**Comment by rgl** [comment]
Closed in https://github.com/rgl/windows-vagrant/commit/26068ebdfca4f46edf89438f76446d17e90a7de0
