### ISSUE TITLE
packer: command not found

### ISSUE THREAD

**Issue by ced455** [rgl/windows-vagrant#16]
Hello, after following your readme using the script inside provided I opened the shell session in : 

C:\tools\msys64\mingw64.exe

Then i ran `make build-windows-2019-virtualbox` and got this error : 

```
rm -f windows-2019-amd64-virtualbox.box
CHECKPOINT_DISABLE=1 PACKER_LOG=1 PACKER_LOG_PATH=windows-2019-amd64-virtualbox-packer-init.log \
        packer init windows-2019.pkr.hcl
/bin/sh: line 1: packer: command not found
make: *** [Makefile:65: windows-2019-amd64-virtualbox.box] Error 127
```

Any Idea why this would happen ? 

Packer - 1.7.8
Vagrant - 2.2.19

Thank you.

**Comment by rgl** [comment]
You might need to restart the shell, for it to pick up the `PATH` environment variable changes.

**Comment by ced455** [comment]
Thanks !

Editing the editing the other .ini files to have `MSYS2_PATH_TYPE=inherit` (like in msys2.ini). Did the job !
