### ISSUE TITLE
Windows 2016 build issues on ubuntu host...

### ISSUE THREAD

**Issue by salderma** [rgl/windows-vagrant#17]
Hi, I have both virtualbox and libvirt installed, trying to build your VMs for both virt providers.

Not sure what's going on, can you shed some light?

LIBVIRT: `make build-windows-2016-libvirt`
```
==> qemu.windows-2016-amd64: Waiting for SSH to become available...
==> qemu.windows-2016-amd64: Connected to SSH!
==> qemu.windows-2016-amd64: Provisioning with Powershell...
==> qemu.windows-2016-amd64: Provisioning with powershell script: disable-windows-updates.ps1
==> qemu.windows-2016-amd64: Error processing command: Error uploading ps script containing env vars: Process exited with status 1
==> qemu.windows-2016-amd64: Step "StepProvision" failed, aborting...
```
Leaves the VM running, sitting with windows UI open and functional if connected to VNC through the build process.

VIRTUALBOX: `make build-windows-2016-virtualbox`
```
==> virtualbox-iso.windows-2016-amd64: Waiting for SSH to become available...
==> virtualbox-iso.windows-2016-amd64: Connected to SSH!
==> virtualbox-iso.windows-2016-amd64: Uploading VirtualBox version info (6.1.32)
==> virtualbox-iso.windows-2016-amd64: Error uploading VirtualBox version: Process exited with status 1
==> virtualbox-iso.windows-2016-amd64: Step "StepUploadVersion" failed, aborting...
```
Leaves VM running, looking at virtualbox console, UI seems functional.

Any ideas?

**Comment by rgl** [comment]
Never seen it fail like that. Take a look at the `.log` files that are on the current directory, they might have more details.

**Comment by rgl** [comment]
This is now fixed. Thanks for letting me known about this problem!

**Comment by salderma** [comment]
Thanks, am running the libvirt build now, and it's well passed this point of failure for me.
