### ISSUE TITLE
Invalid link in doc concerning TMP/TMPDIR packer env variable

### ISSUE THREAD

**Issue by autra** [rgl/windows-vagrant#21]
The README says

> NB if the build fails with something like Post-processor failed: write /tmp/packer073329394/packer-windows-2022-amd64-virtualbox-1505050546-disk001.vmdk: no space left on device you need to increase your temporary partition size or change its location [as described in the packer TMPDIR/TMP environment variable documentation](https://www.packer.io/docs/other/environment-variables.html#tmpdir).

But the link is not valid anymore. I tried searching their doc for the new location, but couldn't find it. Is these variables still supported?

**Comment by rgl** [comment]
The docs URLs have changed in the meantime. That page is now at https://www.packer.io/docs/configure#tmpdir. I will update the README ASAP.

The issue at https://github.com/hashicorp/packer/issues/4296 has more details.
