### ISSUE TITLE
QEMU 7.1 removed -soundhw option

### ISSUE THREAD

**Issue by mbialoru** [rgl/windows-vagrant#22]
According to https://www.qemu.org/docs/master/about/removed-features.html?highlight=soundhw
`-soundhw` option was removed, builds on 7.1.0-5 (arch linux) are failing.
With PACKER_LOG=1 getting a descriptive error:
`packer-builder-qemu plugin: Qemu stderr: qemu-system-x86_64: -soundhw: invalid option`

**Comment by mbialoru** [comment]
Pull request with quick fix available #23

**Comment by rgl** [comment]
The audio device was removed in https://github.com/rgl/windows-vagrant/commit/4d6d382e2e619e718bb980473a9d5563aee4fe7d.

This should now work with recent qemu, so I'm closing this and the related PR.
