### ISSUE TITLE
v7.4.6 Release of PowerShell Hash has changed

### ISSUE THREAD

**Issue by goffinet** [rgl/windows-vagrant#31]
Hello @rgl,

https://github.com/rgl/windows-vagrant/blob/da1a227e62d4078f4fee52afd495ec182abfed27/provision-pwsh.ps1#L32
The value is now
`ED331A04679B83D4C013705282D1F3F8D8300485EB04C081F36E11EAF1148BD0 ` (https://github.com/PowerShell/PowerShell/releases)

**Comment by rgl** [comment]
fixed in https://github.com/rgl/windows-vagrant/pull/32
